name: Auto Cherry-pick to gh-pages (set by @celray)

on:
  push:
    branches:
      - main

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSHER_TOKEN }}

      - name: Set Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Clean specific files in gh-pages branch
        run: |
          git fetch origin
          git checkout gh-pages
          rm -rf * .github/ # This should remove all files and the .github directory
          git add . 
          git commit -m "Clean Documents" || echo "No changes to commit"
          git push origin gh-pages

      - name: Cherry-pick and retain a specific WF to gh-pages
        run: |
          git checkout main
          git fetch origin
          git checkout gh-pages
          git cherry-pick --no-commit ${{ github.sha }}
          
          # Exclude all workflow files and then add back the specific one
          git reset .github/workflows/
          git checkout ${{ github.sha }} -- .github/workflows/re-build-pages.yml
          
          git commit -m "Cherry-picked from main and retained specific workflow"
          git push origin gh-pages
